/**
 * This file was automatically generated by Nexus 0.11.3
 * Do not make changes to this file directly
 */

import * as ctx from "../src/context"
import * as prisma from "./prisma-client/index"


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  AttributeWhereInput: { // input type
    AND?: NexusGenInputs['AttributeWhereInput'][] | null; // [AttributeWhereInput!]
    id?: string | null; // ID
    id_contains?: string | null; // ID
    id_ends_with?: string | null; // ID
    id_gt?: string | null; // ID
    id_gte?: string | null; // ID
    id_in?: string[] | null; // [ID!]
    id_lt?: string | null; // ID
    id_lte?: string | null; // ID
    id_not?: string | null; // ID
    id_not_contains?: string | null; // ID
    id_not_ends_with?: string | null; // ID
    id_not_in?: string[] | null; // [ID!]
    id_not_starts_with?: string | null; // ID
    id_starts_with?: string | null; // ID
    key?: string | null; // String
    key_contains?: string | null; // String
    key_ends_with?: string | null; // String
    key_gt?: string | null; // String
    key_gte?: string | null; // String
    key_in?: string[] | null; // [String!]
    key_lt?: string | null; // String
    key_lte?: string | null; // String
    key_not?: string | null; // String
    key_not_contains?: string | null; // String
    key_not_ends_with?: string | null; // String
    key_not_in?: string[] | null; // [String!]
    key_not_starts_with?: string | null; // String
    key_starts_with?: string | null; // String
    NOT?: NexusGenInputs['AttributeWhereInput'][] | null; // [AttributeWhereInput!]
    OR?: NexusGenInputs['AttributeWhereInput'][] | null; // [AttributeWhereInput!]
    products_every?: NexusGenInputs['ProductWhereInput'] | null; // ProductWhereInput
    products_none?: NexusGenInputs['ProductWhereInput'] | null; // ProductWhereInput
    products_some?: NexusGenInputs['ProductWhereInput'] | null; // ProductWhereInput
    value?: string | null; // String
    value_contains?: string | null; // String
    value_ends_with?: string | null; // String
    value_gt?: string | null; // String
    value_gte?: string | null; // String
    value_in?: string[] | null; // [String!]
    value_lt?: string | null; // String
    value_lte?: string | null; // String
    value_not?: string | null; // String
    value_not_contains?: string | null; // String
    value_not_ends_with?: string | null; // String
    value_not_in?: string[] | null; // [String!]
    value_not_starts_with?: string | null; // String
    value_starts_with?: string | null; // String
  }
  BrandWhereInput: { // input type
    AND?: NexusGenInputs['BrandWhereInput'][] | null; // [BrandWhereInput!]
    id?: string | null; // ID
    id_contains?: string | null; // ID
    id_ends_with?: string | null; // ID
    id_gt?: string | null; // ID
    id_gte?: string | null; // ID
    id_in?: string[] | null; // [ID!]
    id_lt?: string | null; // ID
    id_lte?: string | null; // ID
    id_not?: string | null; // ID
    id_not_contains?: string | null; // ID
    id_not_ends_with?: string | null; // ID
    id_not_in?: string[] | null; // [ID!]
    id_not_starts_with?: string | null; // ID
    id_starts_with?: string | null; // ID
    name?: string | null; // String
    name_contains?: string | null; // String
    name_ends_with?: string | null; // String
    name_gt?: string | null; // String
    name_gte?: string | null; // String
    name_in?: string[] | null; // [String!]
    name_lt?: string | null; // String
    name_lte?: string | null; // String
    name_not?: string | null; // String
    name_not_contains?: string | null; // String
    name_not_ends_with?: string | null; // String
    name_not_in?: string[] | null; // [String!]
    name_not_starts_with?: string | null; // String
    name_starts_with?: string | null; // String
    NOT?: NexusGenInputs['BrandWhereInput'][] | null; // [BrandWhereInput!]
    OR?: NexusGenInputs['BrandWhereInput'][] | null; // [BrandWhereInput!]
    products_every?: NexusGenInputs['ProductWhereInput'] | null; // ProductWhereInput
    products_none?: NexusGenInputs['ProductWhereInput'] | null; // ProductWhereInput
    products_some?: NexusGenInputs['ProductWhereInput'] | null; // ProductWhereInput
  }
  CollectionInput: { // input type
    name: string; // String!
    productsIds?: string[] | null; // [String!]
    ruleSet?: NexusGenInputs['CollectionRuleSetInput'] | null; // CollectionRuleSetInput
  }
  CollectionRuleSetInput: { // input type
    applyDisjunctively: boolean; // Boolean!
    rules: NexusGenInputs['RulesInput'][]; // [RulesInput!]!
  }
  CollectionRuleSetWhereInput: { // input type
    AND?: NexusGenInputs['CollectionRuleSetWhereInput'][] | null; // [CollectionRuleSetWhereInput!]
    appliesDisjunctively?: boolean | null; // Boolean
    appliesDisjunctively_not?: boolean | null; // Boolean
    id?: string | null; // ID
    id_contains?: string | null; // ID
    id_ends_with?: string | null; // ID
    id_gt?: string | null; // ID
    id_gte?: string | null; // ID
    id_in?: string[] | null; // [ID!]
    id_lt?: string | null; // ID
    id_lte?: string | null; // ID
    id_not?: string | null; // ID
    id_not_contains?: string | null; // ID
    id_not_ends_with?: string | null; // ID
    id_not_in?: string[] | null; // [ID!]
    id_not_starts_with?: string | null; // ID
    id_starts_with?: string | null; // ID
    NOT?: NexusGenInputs['CollectionRuleSetWhereInput'][] | null; // [CollectionRuleSetWhereInput!]
    OR?: NexusGenInputs['CollectionRuleSetWhereInput'][] | null; // [CollectionRuleSetWhereInput!]
    rules_every?: NexusGenInputs['CollectionRuleWhereInput'] | null; // CollectionRuleWhereInput
    rules_none?: NexusGenInputs['CollectionRuleWhereInput'] | null; // CollectionRuleWhereInput
    rules_some?: NexusGenInputs['CollectionRuleWhereInput'] | null; // CollectionRuleWhereInput
  }
  CollectionRuleWhereInput: { // input type
    AND?: NexusGenInputs['CollectionRuleWhereInput'][] | null; // [CollectionRuleWhereInput!]
    field?: NexusGenEnums['CollectionRuleField'] | null; // CollectionRuleField
    field_in?: NexusGenEnums['CollectionRuleField'][] | null; // [CollectionRuleField!]
    field_not?: NexusGenEnums['CollectionRuleField'] | null; // CollectionRuleField
    field_not_in?: NexusGenEnums['CollectionRuleField'][] | null; // [CollectionRuleField!]
    id?: string | null; // ID
    id_contains?: string | null; // ID
    id_ends_with?: string | null; // ID
    id_gt?: string | null; // ID
    id_gte?: string | null; // ID
    id_in?: string[] | null; // [ID!]
    id_lt?: string | null; // ID
    id_lte?: string | null; // ID
    id_not?: string | null; // ID
    id_not_contains?: string | null; // ID
    id_not_ends_with?: string | null; // ID
    id_not_in?: string[] | null; // [ID!]
    id_not_starts_with?: string | null; // ID
    id_starts_with?: string | null; // ID
    NOT?: NexusGenInputs['CollectionRuleWhereInput'][] | null; // [CollectionRuleWhereInput!]
    OR?: NexusGenInputs['CollectionRuleWhereInput'][] | null; // [CollectionRuleWhereInput!]
    relation?: NexusGenEnums['CollectionRuleRelation'] | null; // CollectionRuleRelation
    relation_in?: NexusGenEnums['CollectionRuleRelation'][] | null; // [CollectionRuleRelation!]
    relation_not?: NexusGenEnums['CollectionRuleRelation'] | null; // CollectionRuleRelation
    relation_not_in?: NexusGenEnums['CollectionRuleRelation'][] | null; // [CollectionRuleRelation!]
    value?: string | null; // String
    value_contains?: string | null; // String
    value_ends_with?: string | null; // String
    value_gt?: string | null; // String
    value_gte?: string | null; // String
    value_in?: string[] | null; // [String!]
    value_lt?: string | null; // String
    value_lte?: string | null; // String
    value_not?: string | null; // String
    value_not_contains?: string | null; // String
    value_not_ends_with?: string | null; // String
    value_not_in?: string[] | null; // [String!]
    value_not_starts_with?: string | null; // String
    value_starts_with?: string | null; // String
  }
  CollectionWhereInput: { // input type
    AND?: NexusGenInputs['CollectionWhereInput'][] | null; // [CollectionWhereInput!]
    id?: string | null; // ID
    id_contains?: string | null; // ID
    id_ends_with?: string | null; // ID
    id_gt?: string | null; // ID
    id_gte?: string | null; // ID
    id_in?: string[] | null; // [ID!]
    id_lt?: string | null; // ID
    id_lte?: string | null; // ID
    id_not?: string | null; // ID
    id_not_contains?: string | null; // ID
    id_not_ends_with?: string | null; // ID
    id_not_in?: string[] | null; // [ID!]
    id_not_starts_with?: string | null; // ID
    id_starts_with?: string | null; // ID
    name?: string | null; // String
    name_contains?: string | null; // String
    name_ends_with?: string | null; // String
    name_gt?: string | null; // String
    name_gte?: string | null; // String
    name_in?: string[] | null; // [String!]
    name_lt?: string | null; // String
    name_lte?: string | null; // String
    name_not?: string | null; // String
    name_not_contains?: string | null; // String
    name_not_ends_with?: string | null; // String
    name_not_in?: string[] | null; // [String!]
    name_not_starts_with?: string | null; // String
    name_starts_with?: string | null; // String
    NOT?: NexusGenInputs['CollectionWhereInput'][] | null; // [CollectionWhereInput!]
    OR?: NexusGenInputs['CollectionWhereInput'][] | null; // [CollectionWhereInput!]
    products_every?: NexusGenInputs['ProductWhereInput'] | null; // ProductWhereInput
    products_none?: NexusGenInputs['ProductWhereInput'] | null; // ProductWhereInput
    products_some?: NexusGenInputs['ProductWhereInput'] | null; // ProductWhereInput
    rules?: NexusGenInputs['CollectionRuleSetWhereInput'] | null; // CollectionRuleSetWhereInput
  }
  CreateProductInput: { // input type
    attributesIds: NexusGenInputs['UniqueInput'][]; // [UniqueInput!]!
    brand: NexusGenInputs['UniqueInput']; // UniqueInput!
    name: string; // String!
    slug: string; // String!
    variants: NexusGenInputs['CreateVariantInput'][]; // [CreateVariantInput!]!
  }
  CreateVariantInput: { // input type
    availableForSale: boolean; // Boolean!
    optionsValueIds: NexusGenInputs['UniqueInput'][]; // [UniqueInput!]!
    price: number; // Int!
  }
  ImageWhereInput: { // input type
    AND?: NexusGenInputs['ImageWhereInput'][] | null; // [ImageWhereInput!]
    id?: string | null; // ID
    id_contains?: string | null; // ID
    id_ends_with?: string | null; // ID
    id_gt?: string | null; // ID
    id_gte?: string | null; // ID
    id_in?: string[] | null; // [ID!]
    id_lt?: string | null; // ID
    id_lte?: string | null; // ID
    id_not?: string | null; // ID
    id_not_contains?: string | null; // ID
    id_not_ends_with?: string | null; // ID
    id_not_in?: string[] | null; // [ID!]
    id_not_starts_with?: string | null; // ID
    id_starts_with?: string | null; // ID
    NOT?: NexusGenInputs['ImageWhereInput'][] | null; // [ImageWhereInput!]
    OR?: NexusGenInputs['ImageWhereInput'][] | null; // [ImageWhereInput!]
    url?: string | null; // String
    url_contains?: string | null; // String
    url_ends_with?: string | null; // String
    url_gt?: string | null; // String
    url_gte?: string | null; // String
    url_in?: string[] | null; // [String!]
    url_lt?: string | null; // String
    url_lte?: string | null; // String
    url_not?: string | null; // String
    url_not_contains?: string | null; // String
    url_not_ends_with?: string | null; // String
    url_not_in?: string[] | null; // [String!]
    url_not_starts_with?: string | null; // String
    url_starts_with?: string | null; // String
  }
  OptionValueWhereInput: { // input type
    AND?: NexusGenInputs['OptionValueWhereInput'][] | null; // [OptionValueWhereInput!]
    id?: string | null; // ID
    id_contains?: string | null; // ID
    id_ends_with?: string | null; // ID
    id_gt?: string | null; // ID
    id_gte?: string | null; // ID
    id_in?: string[] | null; // [ID!]
    id_lt?: string | null; // ID
    id_lte?: string | null; // ID
    id_not?: string | null; // ID
    id_not_contains?: string | null; // ID
    id_not_ends_with?: string | null; // ID
    id_not_in?: string[] | null; // [ID!]
    id_not_starts_with?: string | null; // ID
    id_starts_with?: string | null; // ID
    name?: string | null; // String
    name_contains?: string | null; // String
    name_ends_with?: string | null; // String
    name_gt?: string | null; // String
    name_gte?: string | null; // String
    name_in?: string[] | null; // [String!]
    name_lt?: string | null; // String
    name_lte?: string | null; // String
    name_not?: string | null; // String
    name_not_contains?: string | null; // String
    name_not_ends_with?: string | null; // String
    name_not_in?: string[] | null; // [String!]
    name_not_starts_with?: string | null; // String
    name_starts_with?: string | null; // String
    NOT?: NexusGenInputs['OptionValueWhereInput'][] | null; // [OptionValueWhereInput!]
    option?: NexusGenInputs['OptionWhereInput'] | null; // OptionWhereInput
    OR?: NexusGenInputs['OptionValueWhereInput'][] | null; // [OptionValueWhereInput!]
  }
  OptionWhereInput: { // input type
    AND?: NexusGenInputs['OptionWhereInput'][] | null; // [OptionWhereInput!]
    id?: string | null; // ID
    id_contains?: string | null; // ID
    id_ends_with?: string | null; // ID
    id_gt?: string | null; // ID
    id_gte?: string | null; // ID
    id_in?: string[] | null; // [ID!]
    id_lt?: string | null; // ID
    id_lte?: string | null; // ID
    id_not?: string | null; // ID
    id_not_contains?: string | null; // ID
    id_not_ends_with?: string | null; // ID
    id_not_in?: string[] | null; // [ID!]
    id_not_starts_with?: string | null; // ID
    id_starts_with?: string | null; // ID
    isColor?: boolean | null; // Boolean
    isColor_not?: boolean | null; // Boolean
    name?: string | null; // String
    name_contains?: string | null; // String
    name_ends_with?: string | null; // String
    name_gt?: string | null; // String
    name_gte?: string | null; // String
    name_in?: string[] | null; // [String!]
    name_lt?: string | null; // String
    name_lte?: string | null; // String
    name_not?: string | null; // String
    name_not_contains?: string | null; // String
    name_not_ends_with?: string | null; // String
    name_not_in?: string[] | null; // [String!]
    name_not_starts_with?: string | null; // String
    name_starts_with?: string | null; // String
    NOT?: NexusGenInputs['OptionWhereInput'][] | null; // [OptionWhereInput!]
    OR?: NexusGenInputs['OptionWhereInput'][] | null; // [OptionWhereInput!]
    values_every?: NexusGenInputs['OptionValueWhereInput'] | null; // OptionValueWhereInput
    values_none?: NexusGenInputs['OptionValueWhereInput'] | null; // OptionValueWhereInput
    values_some?: NexusGenInputs['OptionValueWhereInput'] | null; // OptionValueWhereInput
  }
  ProductTypeWhereInput: { // input type
    AND?: NexusGenInputs['ProductTypeWhereInput'][] | null; // [ProductTypeWhereInput!]
    id?: string | null; // ID
    id_contains?: string | null; // ID
    id_ends_with?: string | null; // ID
    id_gt?: string | null; // ID
    id_gte?: string | null; // ID
    id_in?: string[] | null; // [ID!]
    id_lt?: string | null; // ID
    id_lte?: string | null; // ID
    id_not?: string | null; // ID
    id_not_contains?: string | null; // ID
    id_not_ends_with?: string | null; // ID
    id_not_in?: string[] | null; // [ID!]
    id_not_starts_with?: string | null; // ID
    id_starts_with?: string | null; // ID
    name?: string | null; // String
    name_contains?: string | null; // String
    name_ends_with?: string | null; // String
    name_gt?: string | null; // String
    name_gte?: string | null; // String
    name_in?: string[] | null; // [String!]
    name_lt?: string | null; // String
    name_lte?: string | null; // String
    name_not?: string | null; // String
    name_not_contains?: string | null; // String
    name_not_ends_with?: string | null; // String
    name_not_in?: string[] | null; // [String!]
    name_not_starts_with?: string | null; // String
    name_starts_with?: string | null; // String
    NOT?: NexusGenInputs['ProductTypeWhereInput'][] | null; // [ProductTypeWhereInput!]
    OR?: NexusGenInputs['ProductTypeWhereInput'][] | null; // [ProductTypeWhereInput!]
  }
  ProductWhereInput: { // input type
    AND?: NexusGenInputs['ProductWhereInput'][] | null; // [ProductWhereInput!]
    attributes_every?: NexusGenInputs['AttributeWhereInput'] | null; // AttributeWhereInput
    attributes_none?: NexusGenInputs['AttributeWhereInput'] | null; // AttributeWhereInput
    attributes_some?: NexusGenInputs['AttributeWhereInput'] | null; // AttributeWhereInput
    brand?: NexusGenInputs['BrandWhereInput'] | null; // BrandWhereInput
    collections_every?: NexusGenInputs['CollectionWhereInput'] | null; // CollectionWhereInput
    collections_none?: NexusGenInputs['CollectionWhereInput'] | null; // CollectionWhereInput
    collections_some?: NexusGenInputs['CollectionWhereInput'] | null; // CollectionWhereInput
    description?: string | null; // String
    description_contains?: string | null; // String
    description_ends_with?: string | null; // String
    description_gt?: string | null; // String
    description_gte?: string | null; // String
    description_in?: string[] | null; // [String!]
    description_lt?: string | null; // String
    description_lte?: string | null; // String
    description_not?: string | null; // String
    description_not_contains?: string | null; // String
    description_not_ends_with?: string | null; // String
    description_not_in?: string[] | null; // [String!]
    description_not_starts_with?: string | null; // String
    description_starts_with?: string | null; // String
    id?: string | null; // ID
    id_contains?: string | null; // ID
    id_ends_with?: string | null; // ID
    id_gt?: string | null; // ID
    id_gte?: string | null; // ID
    id_in?: string[] | null; // [ID!]
    id_lt?: string | null; // ID
    id_lte?: string | null; // ID
    id_not?: string | null; // ID
    id_not_contains?: string | null; // ID
    id_not_ends_with?: string | null; // ID
    id_not_in?: string[] | null; // [ID!]
    id_not_starts_with?: string | null; // ID
    id_starts_with?: string | null; // ID
    name?: string | null; // String
    name_contains?: string | null; // String
    name_ends_with?: string | null; // String
    name_gt?: string | null; // String
    name_gte?: string | null; // String
    name_in?: string[] | null; // [String!]
    name_lt?: string | null; // String
    name_lte?: string | null; // String
    name_not?: string | null; // String
    name_not_contains?: string | null; // String
    name_not_ends_with?: string | null; // String
    name_not_in?: string[] | null; // [String!]
    name_not_starts_with?: string | null; // String
    name_starts_with?: string | null; // String
    NOT?: NexusGenInputs['ProductWhereInput'][] | null; // [ProductWhereInput!]
    OR?: NexusGenInputs['ProductWhereInput'][] | null; // [ProductWhereInput!]
    slug?: string | null; // String
    slug_contains?: string | null; // String
    slug_ends_with?: string | null; // String
    slug_gt?: string | null; // String
    slug_gte?: string | null; // String
    slug_in?: string[] | null; // [String!]
    slug_lt?: string | null; // String
    slug_lte?: string | null; // String
    slug_not?: string | null; // String
    slug_not_contains?: string | null; // String
    slug_not_ends_with?: string | null; // String
    slug_not_in?: string[] | null; // [String!]
    slug_not_starts_with?: string | null; // String
    slug_starts_with?: string | null; // String
    thumbnail?: NexusGenInputs['ImageWhereInput'] | null; // ImageWhereInput
    type?: NexusGenInputs['ProductTypeWhereInput'] | null; // ProductTypeWhereInput
    variants_every?: NexusGenInputs['VariantWhereInput'] | null; // VariantWhereInput
    variants_none?: NexusGenInputs['VariantWhereInput'] | null; // VariantWhereInput
    variants_some?: NexusGenInputs['VariantWhereInput'] | null; // VariantWhereInput
  }
  ProductWhereUniqueInput: { // input type
    id?: string | null; // ID
    slug?: string | null; // String
  }
  RulesInput: { // input type
    field: NexusGenEnums['CollectionRuleField']; // CollectionRuleField!
    relation: NexusGenEnums['CollectionRuleRelation']; // CollectionRuleRelation!
    value: string; // String!
  }
  UniqueInput: { // input type
    id: string; // ID!
  }
  UpdateProductInput: { // input type
    attributesIds: NexusGenInputs['UniqueInput'][]; // [UniqueInput!]!
    brand: NexusGenInputs['UniqueInput']; // UniqueInput!
    id: string; // ID!
    name: string; // String!
    variants: NexusGenInputs['UpdateVariantInput'][]; // [UpdateVariantInput!]!
  }
  UpdateVariantInput: { // input type
    availableForSale: boolean; // Boolean!
    id: string; // ID!
    optionsValueIds: NexusGenInputs['UniqueInput'][]; // [UniqueInput!]!
    price: number; // Int!
  }
  VariantWhereInput: { // input type
    AND?: NexusGenInputs['VariantWhereInput'][] | null; // [VariantWhereInput!]
    availableForSale?: boolean | null; // Boolean
    availableForSale_not?: boolean | null; // Boolean
    id?: string | null; // ID
    id_contains?: string | null; // ID
    id_ends_with?: string | null; // ID
    id_gt?: string | null; // ID
    id_gte?: string | null; // ID
    id_in?: string[] | null; // [ID!]
    id_lt?: string | null; // ID
    id_lte?: string | null; // ID
    id_not?: string | null; // ID
    id_not_contains?: string | null; // ID
    id_not_ends_with?: string | null; // ID
    id_not_in?: string[] | null; // [ID!]
    id_not_starts_with?: string | null; // ID
    id_starts_with?: string | null; // ID
    images_every?: NexusGenInputs['ImageWhereInput'] | null; // ImageWhereInput
    images_none?: NexusGenInputs['ImageWhereInput'] | null; // ImageWhereInput
    images_some?: NexusGenInputs['ImageWhereInput'] | null; // ImageWhereInput
    NOT?: NexusGenInputs['VariantWhereInput'][] | null; // [VariantWhereInput!]
    optionValues_every?: NexusGenInputs['OptionValueWhereInput'] | null; // OptionValueWhereInput
    optionValues_none?: NexusGenInputs['OptionValueWhereInput'] | null; // OptionValueWhereInput
    optionValues_some?: NexusGenInputs['OptionValueWhereInput'] | null; // OptionValueWhereInput
    OR?: NexusGenInputs['VariantWhereInput'][] | null; // [VariantWhereInput!]
    price?: number | null; // Int
    price_gt?: number | null; // Int
    price_gte?: number | null; // Int
    price_in?: number[] | null; // [Int!]
    price_lt?: number | null; // Int
    price_lte?: number | null; // Int
    price_not?: number | null; // Int
    price_not_in?: number[] | null; // [Int!]
    sku?: string | null; // String
    sku_contains?: string | null; // String
    sku_ends_with?: string | null; // String
    sku_gt?: string | null; // String
    sku_gte?: string | null; // String
    sku_in?: string[] | null; // [String!]
    sku_lt?: string | null; // String
    sku_lte?: string | null; // String
    sku_not?: string | null; // String
    sku_not_contains?: string | null; // String
    sku_not_ends_with?: string | null; // String
    sku_not_in?: string[] | null; // [String!]
    sku_not_starts_with?: string | null; // String
    sku_starts_with?: string | null; // String
  }
}

export interface NexusGenEnums {
  BrandOrderByInput: "createdAt_ASC" | "createdAt_DESC" | "id_ASC" | "id_DESC" | "name_ASC" | "name_DESC" | "updatedAt_ASC" | "updatedAt_DESC"
  CollectionOrderByInput: "createdAt_ASC" | "createdAt_DESC" | "id_ASC" | "id_DESC" | "name_ASC" | "name_DESC" | "updatedAt_ASC" | "updatedAt_DESC"
  CollectionRuleField: "PRICE" | "TITLE" | "TYPE"
  CollectionRuleRelation: "CONTAINS" | "ENDS_WITH" | "EQUALS" | "GREATER_THAN" | "LESS_THAN" | "NOT_CONTAINS" | "NOT_EQUALS" | "STARTS_WITH"
  ImageOrderByInput: "createdAt_ASC" | "createdAt_DESC" | "id_ASC" | "id_DESC" | "updatedAt_ASC" | "updatedAt_DESC" | "url_ASC" | "url_DESC"
  OptionOrderByInput: "createdAt_ASC" | "createdAt_DESC" | "id_ASC" | "id_DESC" | "isColor_ASC" | "isColor_DESC" | "name_ASC" | "name_DESC" | "updatedAt_ASC" | "updatedAt_DESC"
  OptionValueOrderByInput: "createdAt_ASC" | "createdAt_DESC" | "id_ASC" | "id_DESC" | "name_ASC" | "name_DESC" | "updatedAt_ASC" | "updatedAt_DESC"
  ProductOrderByInput: "createdAt_ASC" | "createdAt_DESC" | "description_ASC" | "description_DESC" | "id_ASC" | "id_DESC" | "name_ASC" | "name_DESC" | "slug_ASC" | "slug_DESC" | "updatedAt_ASC" | "updatedAt_DESC"
  VariantOrderByInput: "availableForSale_ASC" | "availableForSale_DESC" | "createdAt_ASC" | "createdAt_DESC" | "id_ASC" | "id_DESC" | "price_ASC" | "price_DESC" | "sku_ASC" | "sku_DESC" | "updatedAt_ASC" | "updatedAt_DESC"
}

export interface NexusGenRootTypes {
  AggregateBrand: prisma.AggregateBrand;
  AggregateCollection: prisma.AggregateCollection;
  AggregateOption: prisma.AggregateOption;
  AggregateProduct: prisma.AggregateProduct;
  Attribute: prisma.Attribute;
  AttributePayload: { // root type
    name: string; // String!
    values: NexusGenRootTypes['AttributeValue'][]; // [AttributeValue!]!
  }
  AttributeValue: { // root type
    id: string; // ID!
    value: string; // String!
  }
  Brand: prisma.Brand;
  BrandConnection: prisma.BrandConnection;
  BrandEdge: prisma.BrandEdge;
  Collection: prisma.Collection;
  CollectionConnection: prisma.CollectionConnection;
  CollectionEdge: prisma.CollectionEdge;
  Image: prisma.Image;
  Mutation: {};
  Option: prisma.Option;
  OptionConnection: prisma.OptionConnection;
  OptionEdge: prisma.OptionEdge;
  OptionValue: prisma.OptionValue;
  PageInfo: prisma.PageInfo;
  Product: prisma.Product;
  ProductConnection: prisma.ProductConnection;
  ProductEdge: prisma.ProductEdge;
  ProductType: prisma.ProductType;
  Query: {};
  Variant: prisma.Variant;
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  AttributeWhereInput: NexusGenInputs['AttributeWhereInput'];
  BrandWhereInput: NexusGenInputs['BrandWhereInput'];
  CollectionInput: NexusGenInputs['CollectionInput'];
  CollectionRuleSetInput: NexusGenInputs['CollectionRuleSetInput'];
  CollectionRuleSetWhereInput: NexusGenInputs['CollectionRuleSetWhereInput'];
  CollectionRuleWhereInput: NexusGenInputs['CollectionRuleWhereInput'];
  CollectionWhereInput: NexusGenInputs['CollectionWhereInput'];
  CreateProductInput: NexusGenInputs['CreateProductInput'];
  CreateVariantInput: NexusGenInputs['CreateVariantInput'];
  ImageWhereInput: NexusGenInputs['ImageWhereInput'];
  OptionValueWhereInput: NexusGenInputs['OptionValueWhereInput'];
  OptionWhereInput: NexusGenInputs['OptionWhereInput'];
  ProductTypeWhereInput: NexusGenInputs['ProductTypeWhereInput'];
  ProductWhereInput: NexusGenInputs['ProductWhereInput'];
  ProductWhereUniqueInput: NexusGenInputs['ProductWhereUniqueInput'];
  RulesInput: NexusGenInputs['RulesInput'];
  UniqueInput: NexusGenInputs['UniqueInput'];
  UpdateProductInput: NexusGenInputs['UpdateProductInput'];
  UpdateVariantInput: NexusGenInputs['UpdateVariantInput'];
  VariantWhereInput: NexusGenInputs['VariantWhereInput'];
  BrandOrderByInput: NexusGenEnums['BrandOrderByInput'];
  CollectionOrderByInput: NexusGenEnums['CollectionOrderByInput'];
  CollectionRuleField: NexusGenEnums['CollectionRuleField'];
  CollectionRuleRelation: NexusGenEnums['CollectionRuleRelation'];
  ImageOrderByInput: NexusGenEnums['ImageOrderByInput'];
  OptionOrderByInput: NexusGenEnums['OptionOrderByInput'];
  OptionValueOrderByInput: NexusGenEnums['OptionValueOrderByInput'];
  ProductOrderByInput: NexusGenEnums['ProductOrderByInput'];
  VariantOrderByInput: NexusGenEnums['VariantOrderByInput'];
}

export interface NexusGenFieldTypes {
  AggregateBrand: { // field return type
    count: number; // Int!
  }
  AggregateCollection: { // field return type
    count: number; // Int!
  }
  AggregateOption: { // field return type
    count: number; // Int!
  }
  AggregateProduct: { // field return type
    count: number; // Int!
  }
  Attribute: { // field return type
    id: string; // ID!
    key: string; // String!
    products: NexusGenRootTypes['Product'][] | null; // [Product!]
    value: string; // String!
  }
  AttributePayload: { // field return type
    name: string; // String!
    values: NexusGenRootTypes['AttributeValue'][]; // [AttributeValue!]!
  }
  AttributeValue: { // field return type
    id: string; // ID!
    value: string; // String!
  }
  Brand: { // field return type
    id: string; // ID!
    name: string; // String!
    products: NexusGenRootTypes['Product'][] | null; // [Product!]
  }
  BrandConnection: { // field return type
    aggregate: NexusGenRootTypes['AggregateBrand']; // AggregateBrand!
    edges: NexusGenRootTypes['BrandEdge'][]; // [BrandEdge!]!
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BrandEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['Brand']; // Brand!
  }
  Collection: { // field return type
    attributes: NexusGenRootTypes['AttributePayload'][]; // [AttributePayload!]!
    brands: NexusGenRootTypes['Brand'][]; // [Brand!]!
    id: string; // ID!
    name: string; // String!
    options: NexusGenRootTypes['Option'][]; // [Option!]!
    products: NexusGenRootTypes['ProductConnection']; // ProductConnection!
  }
  CollectionConnection: { // field return type
    aggregate: NexusGenRootTypes['AggregateCollection']; // AggregateCollection!
    edges: NexusGenRootTypes['CollectionEdge'][]; // [CollectionEdge!]!
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  CollectionEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['Collection']; // Collection!
  }
  Image: { // field return type
    id: string; // ID!
    url: string; // String!
  }
  Mutation: { // field return type
    addToCart: boolean; // Boolean!
    collectionAddProducts: NexusGenRootTypes['Collection']; // Collection!
    collectionCreate: NexusGenRootTypes['Collection']; // Collection!
    collectionRemoveProducts: NexusGenRootTypes['Collection']; // Collection!
    collectionUpdate: NexusGenRootTypes['Collection']; // Collection!
    productCreate: NexusGenRootTypes['Product']; // Product!
    productDelete: NexusGenRootTypes['Product']; // Product!
    productUpdate: NexusGenRootTypes['Product']; // Product!
    removeFromCart: boolean; // Boolean!
  }
  Option: { // field return type
    id: string; // ID!
    isColor: boolean; // Boolean!
    name: string; // String!
    values: NexusGenRootTypes['OptionValue'][] | null; // [OptionValue!]
  }
  OptionConnection: { // field return type
    aggregate: NexusGenRootTypes['AggregateOption']; // AggregateOption!
    edges: NexusGenRootTypes['OptionEdge'][]; // [OptionEdge!]!
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  OptionEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['Option']; // Option!
  }
  OptionValue: { // field return type
    id: string; // ID!
    name: string; // String!
    option: NexusGenRootTypes['Option']; // Option!
  }
  PageInfo: { // field return type
    endCursor: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor: string | null; // String
  }
  Product: { // field return type
    attributes: NexusGenRootTypes['Attribute'][]; // [Attribute!]!
    brand: NexusGenRootTypes['Brand']; // Brand!
    description: string; // String!
    id: string; // ID!
    name: string; // String!
    slug: string; // String!
    thumbnail: NexusGenRootTypes['Image']; // Image!
    type: NexusGenRootTypes['ProductType'] | null; // ProductType
    variants: NexusGenRootTypes['Variant'][] | null; // [Variant!]
  }
  ProductConnection: { // field return type
    aggregate: NexusGenRootTypes['AggregateProduct']; // AggregateProduct!
    edges: NexusGenRootTypes['ProductEdge'][]; // [ProductEdge!]!
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  ProductEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['Product']; // Product!
  }
  ProductType: { // field return type
    id: string; // ID!
    name: string; // String!
  }
  Query: { // field return type
    brands: NexusGenRootTypes['BrandConnection']; // BrandConnection!
    collection: NexusGenRootTypes['Collection']; // Collection!
    collections: NexusGenRootTypes['CollectionConnection']; // CollectionConnection!
    options: NexusGenRootTypes['OptionConnection']; // OptionConnection!
    product: NexusGenRootTypes['Product'] | null; // Product
    products: NexusGenRootTypes['ProductConnection']; // ProductConnection!
  }
  Variant: { // field return type
    availableForSale: boolean | null; // Boolean
    id: string; // ID!
    images: NexusGenRootTypes['Image'][] | null; // [Image!]
    optionValues: NexusGenRootTypes['OptionValue'][] | null; // [OptionValue!]
    price: number; // Int!
    sku: string | null; // String
  }
}

export interface NexusGenArgTypes {
  Attribute: {
    products: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenEnums['ProductOrderByInput'] | null; // ProductOrderByInput
      skip?: number | null; // Int
      where?: NexusGenInputs['ProductWhereInput'] | null; // ProductWhereInput
    }
  }
  Brand: {
    products: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenEnums['ProductOrderByInput'] | null; // ProductOrderByInput
      skip?: number | null; // Int
      where?: NexusGenInputs['ProductWhereInput'] | null; // ProductWhereInput
    }
  }
  Collection: {
    products: { // args
      attributesIds?: string[] | null; // [ID!]
      brandsIds?: string[] | null; // [ID!]
      first?: number | null; // Int
      last?: number | null; // Int
      optionsValuesIds?: string[] | null; // [ID!]
    }
  }
  Mutation: {
    addToCart: { // args
      variantId: string; // ID!
    }
    collectionAddProducts: { // args
      collectionId: string; // ID!
      productIds: string[]; // [ID!]!
    }
    collectionCreate: { // args
      collection: NexusGenInputs['CollectionInput']; // CollectionInput!
    }
    collectionRemoveProducts: { // args
      collectionId: string; // ID!
      productIds: string[]; // [ID!]!
    }
    collectionUpdate: { // args
      collection: NexusGenInputs['CollectionInput']; // CollectionInput!
      id: string; // ID!
    }
    productCreate: { // args
      data: NexusGenInputs['CreateProductInput']; // CreateProductInput!
    }
    productDelete: { // args
      productId: string; // ID!
    }
    productUpdate: { // args
      data: NexusGenInputs['UpdateProductInput']; // UpdateProductInput!
    }
    removeFromCart: { // args
      variantId: string; // ID!
    }
  }
  Option: {
    values: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenEnums['OptionValueOrderByInput'] | null; // OptionValueOrderByInput
      skip?: number | null; // Int
      where?: NexusGenInputs['OptionValueWhereInput'] | null; // OptionValueWhereInput
    }
  }
  Product: {
    variants: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenEnums['VariantOrderByInput'] | null; // VariantOrderByInput
      skip?: number | null; // Int
      where?: NexusGenInputs['VariantWhereInput'] | null; // VariantWhereInput
    }
  }
  Query: {
    brands: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenEnums['BrandOrderByInput'] | null; // BrandOrderByInput
      skip?: number | null; // Int
      where?: NexusGenInputs['BrandWhereInput'] | null; // BrandWhereInput
    }
    collection: { // args
      collectionId: string; // ID!
    }
    collections: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenEnums['CollectionOrderByInput'] | null; // CollectionOrderByInput
      skip?: number | null; // Int
      where?: NexusGenInputs['CollectionWhereInput'] | null; // CollectionWhereInput
    }
    options: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenEnums['OptionOrderByInput'] | null; // OptionOrderByInput
      skip?: number | null; // Int
      where?: NexusGenInputs['OptionWhereInput'] | null; // OptionWhereInput
    }
    product: { // args
      where: NexusGenInputs['ProductWhereUniqueInput']; // ProductWhereUniqueInput!
    }
    products: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenEnums['ProductOrderByInput'] | null; // ProductOrderByInput
      skip?: number | null; // Int
      where?: NexusGenInputs['ProductWhereInput'] | null; // ProductWhereInput
    }
  }
  Variant: {
    images: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenEnums['ImageOrderByInput'] | null; // ImageOrderByInput
      skip?: number | null; // Int
      where?: NexusGenInputs['ImageWhereInput'] | null; // ImageWhereInput
    }
    optionValues: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenEnums['OptionValueOrderByInput'] | null; // OptionValueOrderByInput
      skip?: number | null; // Int
      where?: NexusGenInputs['OptionValueWhereInput'] | null; // OptionValueWhereInput
    }
  }
}

export interface NexusGenAbstractResolveReturnTypes {
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = "AggregateBrand" | "AggregateCollection" | "AggregateOption" | "AggregateProduct" | "Attribute" | "AttributePayload" | "AttributeValue" | "Brand" | "BrandConnection" | "BrandEdge" | "Collection" | "CollectionConnection" | "CollectionEdge" | "Image" | "Mutation" | "Option" | "OptionConnection" | "OptionEdge" | "OptionValue" | "PageInfo" | "Product" | "ProductConnection" | "ProductEdge" | "ProductType" | "Query" | "Variant";

export type NexusGenInputNames = "AttributeWhereInput" | "BrandWhereInput" | "CollectionInput" | "CollectionRuleSetInput" | "CollectionRuleSetWhereInput" | "CollectionRuleWhereInput" | "CollectionWhereInput" | "CreateProductInput" | "CreateVariantInput" | "ImageWhereInput" | "OptionValueWhereInput" | "OptionWhereInput" | "ProductTypeWhereInput" | "ProductWhereInput" | "ProductWhereUniqueInput" | "RulesInput" | "UniqueInput" | "UpdateProductInput" | "UpdateVariantInput" | "VariantWhereInput";

export type NexusGenEnumNames = "BrandOrderByInput" | "CollectionOrderByInput" | "CollectionRuleField" | "CollectionRuleRelation" | "ImageOrderByInput" | "OptionOrderByInput" | "OptionValueOrderByInput" | "ProductOrderByInput" | "VariantOrderByInput";

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = "Boolean" | "Float" | "ID" | "Int" | "String";

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: ctx.Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}